### PR TITLE
Some fixes and improvement

### PR DESCRIPTION
**Pull request by psolyca**
Hi,

Some fixes for Python 3 compatibility cause I had some trouble running it with Winpython 3.4.3.

Also, I added the angle and distance unit support for the GSI file parser.

### CODE REVIEW

**Comment by psolyca** [comment]
Ok, for now I had a problem with dms angle falling with the 16 bits GSI file (Travis is complaining).
I will pull it back later.

**Comment by steko** [comment]
Thank you for submitting this pull request, I'm sorry I didn't see it earlier.

The current version of TOPS is not meant to be compatible with Python 3 and I'm happy if you can make it work with such small changes, but my plan is to ditch Python 2 and switch to Python 3 with the next version https://github.com/steko/totalopenstation/milestones/v0.5 so any pull request in that direction will be very useful once work on 0.5 starts (hopefully soon).

The fix for GSI angles is very welcome: if you can, it would be good to have a sample data file and a few unit tests to cover the new variants in the GSI format (it should be easy if you look at the existing unit tests for the GSI module). In fact, the best thing would be to have separate pull requests for the separate fixes you're proposing, so we can work on them separately. What do you think?

**Comment by psolyca** [comment]
Hi,

Not a big trouble that you did not see my pull request as it is a big mess. I begin with coding and git so I am commiting, reverting, pushing not always in the right order.

Ok for Python 3, I will revert my issue5 branch and save my Python 3 compatibility commits in patches for now.
I have installed a Python2 environnement and begun to work with it.

For the GSI file parser, I am ok. I have an other sample file even if sample files in the repository covered lots of GSI codes.

**Comment by steko** [comment]
Dear Damien,
I'm happy to help you with creating a better pull request. You could for example do as follows:
- add your sample file
- add the same improvements to GSI that were in this pull request
- add some unit tests (or I will do this if you don't feel comfortable)

The Travis failures were caused by a wrong object type in the case of DDD.MMSS conversion: we need to make sure that the changes you introduced don't break the following steps in the data processing chain.

Also, I note that you have [used the same variable name twice here](https://github.com/psolyca/totalopenstation/blob/58b33367fc8dab4b613f909074e2b247f84f400e/totalopenstation/formats/leica_gsi.py#L95).

**Comment by psolyca** [comment]
I already have done the work again.
I am adding some new unit test.

For Travis, I am trying to do unit test on my computer first and everything is OK for now.

For the use of the same variable name is because I did not want a long line, so I override it and use the first variable in the second. If you prefer, I can avoid it.

**Pull request closed without merging**
