### PR TITLE
Change DMS type from string to dictionary

### PR DESCRIPTION
**Pull request by psolyca**
Here are the changes to DMS type.

### CODE REVIEW

**Comment by steko** [comment]
Thanks! It would be nice to have an entire data file with DMS angle data, and milliseconds, to have more extensive tests. If you have one, just add it to the `sample_data/leica_gsi` directory :wink:

**Comment by steko** [comment]
Pinging #31 for the record

**Comment by psolyca** [comment]
The sample data file "leica_gsi16_gurob.gsi" has all angles in DMS format.
The sample data file "leica_gsi8_ertola.gsi" is in gon.

**Comment by steko** [comment]
Yes, it would be even better to have a sample data file with milliseconds, too, but what we have is already good. Thank you!

**Comment by psolyca** [comment]
You always have milliseconds in DMS Leica format.
The Nikon RAW v2.00 do not use milliseconds (as I have seen in the sample file) that is why I forced milliseconds to "0" in nikon_raw_v200.py. I have an other file from a Trimble station to complete the format later.
I did not see any other format with DMS angle type for now. I prefer to work on GSI parser to begin as I know more the format. I will investigate later for others.

**Pull request merged**
