### PR TITLE
Add raw data parsing to enable calculation with polar data

### PR DESCRIPTION
**Pull request by psolyca**
Ok, here is a WIP of a more complete data parsing firstly on GSI file.
This method will be applied on the other parsing scripts.

The goal is to be able to calculate and analyse data, looking for errors, change coordinates systems, do everything a surveyor need to do with these data till drawing...

I will amend this PR so do not merge it now. It is for information purpose and if you want to discuss.

I think the Travis test suit will not pass cause I did not change the test behaviour.

### CODE REVIEW

**Comment by steko** [comment]
The PR adds many improvements that I wish to merge as soon as possible. I'm a bit worried about introducing so many changes in a single commit, so if you can, it would be really great to have one commit per feature:
- the GSI improvements (`UNITS`, `_get_comments` etc.)
- the angle conversion functions (I think they should be in `polar.py` though?)
- the ”raw data” command line option and data parser function

I will keep an eye for your further work on the PR and I'm happy to help you in improving the good work you've done here.

**Comment by psolyca** [comment]
The angle conversion is not the only conversion I added, I also have a horizontal to slope conversion maybe some others, that is why I added a file for that purpose.

**Comment by steko** [comment]
Right, the `totalopenstation.utils` module is more suited for stuff that is used by the application (user preferences, scanning serial ports, etc.), but `conversion.py` should be under `totalopenstation.formats` with all other code dealing with data import. You should also edit the file header with the correct file name and add yourself as the author :wink: 

You removed `.gitignore` in 1689acdbfa3e79e9d7f265e5317475c14350d6c4 

In 3114b2aace1f21c366d6d77af89932314b4d92e3 there are two things I'd like to discuss:
1. the `desc` argument is a shortcode for _description_ which is probably what you meant with `point_name` (otherwise all points will have `desc = "PT"`)
2. the `Feature` class will take any further init argument into the `properties` dictionary, and my idea was that this dictionary could be used to store all extra data as that retrieved by your raw parser improvements: do you think it could be used for that purpose?

**Comment by psolyca** [comment]
Ok I will move `conversion.py` to `totalopenstations.formats`.

I remove `.gitignore` cause I use a general gitignore file for all my repositories. If you want, I can add one in the next commit.

I was looking for a method to link a station to all related data to this station; points coordinates, backsight,... like the way it is with LandXML. So I will remove the  `point_name` argument.
I thought about using `FeatureCollection` but I would like to add a `properties` or `id` value to distinguish all `FeatureCollection`. Maybe I will need a collection of `FeatureCollection`.

Lastly, I also tried to replace GeoJSON with LandXML. It is better for ordering data but it is slower, maybe I do not use the better library, I used `xml.etree.ElementTree`, I will try with lxml.

**Comment by steko** [comment]
Perhaps my previous comment was a bit confused: I meant to say that `point_name` could be put in `properties` and will be accessed like any other property.

GeoJSON vs LandXML: I would be very happy if we could support LandXML :grinning: but every time I look at the specification I'm turned away. It's true that our use case is perhaps 10% of the entire spec. So for now I chose GeoJSON, which is easy to convert to output formats and plays well with GIS software. I'm not an expert in Python XML libraries, but how slow is slower in your tests? I recommend you take a look at [xmldict](https://github.com/thoughtnirvana/xmldict), a nice library that makes it less painful to work with XML, basically using a nested dictionary structure. Furthermore, I don't know how widespread LandXML actually is, regardless of whether it offers a better data model for total station data. It would be fantastic if you could show me a short, working example of a set of total station measurements encoded in LandXML. 

To keep all points and measurements tied/linked to their station of source, we could have an option to produce one `FeatureCollection` per station for the moment being.

**Comment by psolyca** [comment]
Ok Travis has failed cause parsers Nikon and Topcon are not up to date.

I have updated Leica GSI and Carlson RW5 parsers.
I will move conversion.py to totalopenstation.formats next time.
I also have to add myself to the author ^^

**Comment by psolyca** [comment]
So for now I make a break on adding more file parser as I do not have enough test files.
I should be able to parse zeiss but I want to improve polar data computing.

I am not merging for now as I have some feature to add to already enhanced parsers.

**Comment by steko** [comment]
Thank you, I'll try to go through your pull request in the next days so we can at least merge the parts that don't require big changes, release 0.4 and then move on integrating your bigger changes. It looks very promising! :smiley:

**Comment by psolyca** [comment]
Before merging it could be could good to fix the issue #66 of this morning. If you do not have enough time I will investigate it.

**Comment by steko** [comment]
I merged your pull request! Sorry it took so long, there were a lot of changes I needed to review. You did an excellent work, especially with the GSI format :+1:

**Comment by psolyca** [comment]
No problem. We just need some tester now.

**Pull request merged**
