### PR TITLE
small fixes to documentation structure and sphinx theme sidebar

### PR DESCRIPTION
**Pull request by steko**
This pull request is aimed at small improvements to the current Sphinx documentation, both in structure (toctree directives) and look (sidebar provided by default alabaster theme).

### CODE REVIEW

**Comment by steko** [comment]
The compiled docs with these changes can be seen (temporarily) at https://totalopenstation.readthedocs.io/en/xx-fix-sphinx-theme/

**Comment by steko** [comment]
I think it's useful to clarify that this pull request doesn't fix issue #82 - even though redefining the general structure of the documentation will be necessary.

**Review by psolyca — APPROVED** [review]
Ok, good for me

**Comment by steko** [comment]
Thank you! Can you do the merge into master?

**Pull request merged**
