### PR TITLE
Documentation : Leica GSI #2

### PR DESCRIPTION
**Pull request by psolyca**
PR #70  need to be accepted before this one (even if this one is complete against master branch).

This PR add :
- a complete documentation of Leica GSI format,
- autodoc directive for Sphinx,
- some more docstrings in module parser.

### CODE REVIEW

**Comment by steko** [comment]
Very good job here at improving the documentation! 👏 
I'm not entirely convinced we need `autodoc` but I trust your judgement. Sphinx returns me one error:

```
docs (psolyca-doc/leica_GSI*) » make html                                                                                                                                           ~/code/totalopenstation/docs  
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.5.2
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 26 source files that are out of date
updating environment: 26 added, 0 changed, 0 removed
reading sources... [100%] users                                                                                                                                                                                    
/home/steko/code/totalopenstation/docs/input_formats/if_leica_gsi.rst:488: WARNING: autodoc: failed to import module u'formats.leica_gsi'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/steko/code/totalopenstation/totalopenstation/formats/__init__.py", line 35, in <module>
    class Feature(g.Feature):
AttributeError: 'module' object has no attribute 'Feature'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] users                                                                                                                                                                                     
generating indices... genindex py-modindex
writing additional pages... search
copying static files... WARNING: favicon file 'tops.ico' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.

Build finished. The HTML pages are in _build/html.
```

Let's fix that before merging? 🙏

**Comment by psolyca** [comment]
For autodoc, it was not my first idea but we need to comment the code if other person wants to join us so I thought to use those comments to complete the documentation.

For the error, I have an import error but I am changing right now my environment from windows to Linux and I did not finalize my configuration.
Have you tried compiling the doc with readthedoc ? I have seen that I can compile on readthedoc but not on my computer (old environment) and if I change something, it is the opposite ! Do not know why, I tried to have a general conf.py but I will investigate.

Are you using virtual environments or not ?

**Comment by psolyca** [comment]
I am using a virtualenv.
I reinstall Sphinx in the virtualenv otherwise I have an ImportError (do not want to mess mor conf.py) and I do not have the AttributeError message.

```
(totalopenstation) dev@vps456794:~/repositories/totalopenstation/docs$ git branch
  doc/Carlson_RW5
  doc/Nikon_RAW
* doc/leica_GSI
  doc/main
  feature/LandXML
  feature/LandXML_improvement
  feature/Tk_gui
  feature/Tkinter_gui
  feature/lxml
  feature/rework_carlson_rw5_parser
  gh-pages
  master
  py3_preparation
(totalopenstation) dev@vps456794:~/repositories/totalopenstation/docs$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.4
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
/home/dev/.virtualenvs/totalopenstation/local/lib/python2.7/site-packages/sphinx/environment/__init__.py:685: RemovedInSphinx17Warning: html_use_smartypants option is deprecated. Smart quotes are on by default; if you want to disable or customize them, use the smart_quotes option in docutils.conf.
  RemovedInSphinx17Warning)

/home/dev/repositories/totalopenstation/docs/input_formats/if_nikon_raw_v200.rst:18: WARNING: Include file u'/home/dev/repositories/totalopenstation/sample_data/nikon_raw_v200.tops' not found or reading it failed
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/dev/repositories/totalopenstation/docs/input_formats/new.rst: WARNING: document isn't included in any toctree
/home/dev/repositories/totalopenstation/docs/interfaces/cli_connector.rst: WARNING: document isn't included in any toctree
/home/dev/repositories/totalopenstation/docs/interfaces/cli_parser.rst: WARNING: document isn't included in any toctree
/home/dev/repositories/totalopenstation/docs/interfaces/gui_main.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] input_formats/main
generating indices... genindex py-modindex
writing additional pages... search
copying static files... WARNING: favicon file 'tops.ico' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 6 warnings.

Build finished. The HTML pages are in _build/html.
```
The branch is not up to date with your merge.

**Comment by steko** [comment]
Ok, I need to recheck - I probably forgot activating the virtualenv when running the command that gave me the AttributeError (and it seems we're using different Sphinx versions, so I agree with you about installing Sphinx in the virtualenv).
Il 20 ottobre 2017 alle 9.25 Damien Gaignon <notifications@github.com> ha scritto:I am using a virtualenv.
I reinstall Sphinx in the virtualenv otherwise I have an ImportError (do not want to mess mor conf.py) and I do not have the AttributeError message.
(totalopenstation) dev@vps456794:~/repositories/totalopenstation/docs$ git branch
  doc/Carlson_RW5
  doc/Nikon_RAW
* doc/leica_GSI
  doc/main
  feature/LandXML
  feature/LandXML_improvement
  feature/Tk_gui
  feature/Tkinter_gui
  feature/lxml
  feature/rework_carlson_rw5_parser
  gh-pages
  master
  py3_preparation
(totalopenstation) dev@vps456794:~/repositories/totalopenstation/docs$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.4
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
/home/dev/.virtualenvs/totalopenstation/local/lib/python2.7/site-packages/sphinx/environment/__init__.py:685: RemovedInSphinx17Warning: html_use_smartypants option is deprecated. Smart quotes are on by default; if you want to disable or customize them, use the smart_quotes option in docutils.conf.
  RemovedInSphinx17Warning)

/home/dev/repositories/totalopenstation/docs/input_formats/if_nikon_raw_v200.rst:18: WARNING: Include file u'/home/dev/repositories/totalopenstation/sample_data/nikon_raw_v200.tops' not found or reading it failed
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/dev/repositories/totalopenstation/docs/input_formats/new.rst: WARNING: document isn't included in any toctree
/home/dev/repositories/totalopenstation/docs/interfaces/cli_connector.rst: WARNING: document isn't included in any toctree
/home/dev/repositories/totalopenstation/docs/interfaces/cli_parser.rst: WARNING: document isn't included in any toctree
/home/dev/repositories/totalopenstation/docs/interfaces/gui_main.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] input_formats/main
generating indices... genindex py-modindex
writing additional pages... search
copying static files... WARNING: favicon file 'tops.ico' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 6 warnings.

Build finished. The HTML pages are in _build/html.

The branch is not up to date with your merge.

**Comment by steko** [comment]
Ok, the error on my side was caused by the old Sphinx version, installing the current stable version in the virtualenv fixed the issue. Merge on the way 👟

**Comment by steko** [comment]
Ah well, Read the Docs is running Sphinx 1.5.3 😦 so the automodule section on the [documentation page](https://totalopenstation.readthedocs.io/en/latest/input_formats/if_leica_gsi.html#module-documentation) is empty 🕳

**Pull request merged**
