### PR TITLE
Update tops_dxf.py

### PR DESCRIPTION
**Pull request by mach0**
corrected typo and name layers in english

### CODE REVIEW

**Comment by steko** [comment]
The Italian layer names were a residue from the original implementation of DXF output, as it was requested by a colleague of mine. I would literally translate them in the plural form, as `POINTS`, `QUOTES` and `NUMBERS` but perhaps a better choice would be `POINTS`, `Z_COORDS` and `LABELS` (since point ids are not necessarily numbers?). What do you think?

**Comment by mach0** [comment]
Good Idea .. I changed it in the PR.
Is there a way to NOT create so many layers but rather write everything into one?

**Comment by psolyca** [comment]
Sorry for the delay.
If you look at the code (tops_dxf.py), there is the option to separate the layers or not, the default are layers separated.
By the way there is no option on command line to handle this for now.

You can add a commit with the following modifications :

- https://github.com/psolyca/totalopenstation/blob/bef412faaf52a36f1d6225d1aed8627008842fc3/scripts/totalopenstation-cli-parser.py#L90

```Python
parser.add_option("-s",
            "--singlelayer",
            action="store_false",
            dest="singlelayer",
            default=True,
            help=_("single layer ONLY for dxf output format"))
```

- https://github.com/psolyca/totalopenstation/blob/bef412faaf52a36f1d6225d1aed8627008842fc3/scripts/totalopenstation-cli-parser.py#L172 :
```Python
if options.outformat == "dxf":
    output = outputclass(parsed_points, options.singlelayer)
else:
    output = outputclass(parsed_points)
```

**Review by steko — APPROVED** [review]

**Comment by steko** [comment]
> 
> By the way there is no option on command line to handle this for now.
> 
> You can add a commit with the following modifications :

The problem is that it doesn't make much sense from my point of view to offer this feature in the command line and not in the GUI. See the discussion in #5

**Comment by steko** [comment]
I closed this pull request by mistake. I will pull anyway soon and merge into master.

**Comment by steko** [comment]
Merged in 5744f12047feb73e1011962655ff4d70fc55155d.

Thanks @mach0 !

**Pull request closed without merging**
