### PR TITLE
Documentation : base of documentation #2

### PR DESCRIPTION
**Pull request by psolyca**
Second try and this one is the good one.

This PR is the base of other PR related to documentation which will come later.

It add :
- Autodoc and napoleon extension to Sphinx,
- A global directive for page enhancement,
- Some little corrections,
- Rework the structure of some pages needed for futher update.

### CODE REVIEW

**Comment by steko** [comment]
I'm looking into merging this large pull request, since it's a foundation for further changes (and a lot of work 😁 🔝 )

There are some warnings for me when building the docs, pasted below. Could you confirm that you encounter the same warnings?

```
docs (psolyca-doc/main*) » make html                                                                                                                                                ~/code/totalopenstation/docs  
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.5.2
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 26 source files that are out of date
updating environment: 26 added, 0 changed, 0 removed
reading sources... [100%] users                                                                                                                                                                                    
/home/steko/code/totalopenstation/docs/input_formats/if_nikon_raw_v200.rst:18: WARNING: Include file u'/home/steko/code/totalopenstation/sample_data/nikon_raw_v200.tops' not found or reading it failed
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/steko/code/totalopenstation/docs/input_formats/new.rst:: WARNING: document isn't included in any toctree
/home/steko/code/totalopenstation/docs/interfaces/cli_connector.rst:: WARNING: document isn't included in any toctree
/home/steko/code/totalopenstation/docs/interfaces/cli_parser.rst:: WARNING: document isn't included in any toctree
/home/steko/code/totalopenstation/docs/interfaces/gui_main.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] users                                                                                                                                                                                     
/home/steko/code/totalopenstation/docs/interfaces/cli_connector.rst:31: WARNING: unknown option: --model
/home/steko/code/totalopenstation/docs/interfaces/cli_connector.rst:31: WARNING: unknown option: --port
/home/steko/code/totalopenstation/docs/interfaces/cli_parser.rst:45: WARNING: unknown option: --raw
generating indices... genindex py-modindex
writing additional pages... search
copying static files... WARNING: favicon file 'tops.ico' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 9 warnings.

Build finished. The HTML pages are in _build/html.
```

**Comment by psolyca** [comment]
Hello !

Yes I had the same warnings.
I did not look at each warning cause the result seems ok.

**Comment by steko** [comment]
I think the only warnings that must be resolved are the 4 documents that are not included in any toctree directive (they're basically unreachable for readers of the documentation).

Il 11 ottobre 2017 08:03:56 CEST, Damien Gaignon <notifications@github.com> ha scritto:

**Comment by psolyca** [comment]
There are not in any toctree but their links are : 
- in input_format/main.html for new.html (.rst)
- in interfaces/main.html for the 3 others
So these documentations can be reached.
In my final version by the way and if you merge this one, others are coming soon.
My git is up to date with all documentation and I have a private readthedocs to test all documentation build.

EDIT : Maybe you can reache the last version as it is public http://tops.readthedocs.io/en/latest/

**Comment by steko** [comment]
Ok, 

>  So these documentations can be reached.

But we should be adding a `:hidden:` directive to make sure those pages are not excluded from indices and the PDF manual: http://www.sphinx-doc.org/en/stable/markup/toctree.html (the PDF manual is an important documentation item).

I fixed all those warnings except from the favicon missing and merged.

**Pull request merged**
