### PR TITLE
Add angle and distance for GSI parser

### PR DESCRIPTION
**Pull request by psolyca**
Hi,

Here is the angle and distance units support for GSI parser.
I also added test for the 8bits example and fixe the 16bits test.
The 16bits test was faulty because Leica sexagesimal use millisecond and not secondes like Nikon Raw.

### CODE REVIEW

**Comment by steko** [comment]
Damien, looks great! I'm going to merge this right now, and I will add your name to the AUTHORS if you agree.

Do you think it would be easier to pass around the DMS angle data as a dictionary (with one key/value for D, M, S and milliseconds) instead of slicing strings?

**Comment by psolyca** [comment]
Yes I think it is possible and why a dictionary and not a tuple ( D, M, S, ml) ?

**Comment by steko** [comment]
A tuple is certainly faster, but it makes the code less explicit and more difficult to understand for someone who is not familiar with TOPS, I think?

**Comment by psolyca** [comment]
Why the second commit (https://github.com/psolyca/totalopenstation/commit/29d2d1fe3384363e99f7ece3659e241ac448e353) do not merge?

Have a look here https://github.com/psolyca/totalopenstation/commit/d25804d2bcc36037bfb4347d2a2d81e04f7772e0 to see if the way I did it is good for you.

**Comment by steko** [comment]
I messed up the merge, I didn't realise it was branched off `issue5`. Now it's fixed.

Could you put the work on DMS angles in a new branch? I think it's good and you should create a pull request! :+1:

**Pull request merged**
