### PR TITLE
fix #157: binary data from download need to be saved as binary

### LINKED ISSUE #157: [BUG] totalopenstaion-cli-connector: output file is binary
When try to export the file via totalopenstaion-cli-connector.py I have an error . The outputfile should be  binary and not string. So I suggest to change on line 97 

e=open(options.outfile, 'w')
to 
e=open(options.outfile, 'wb')

this works for me

### PR DESCRIPTION
**Pull request by steko**
Fixes #157

### CODE REVIEW

**Comment by steko** [comment]
Fixes #157

**Comment by steko** [comment]
Hey @enzococca @psolyca do you have any feedback on this PR?

If you could confirm that it works as expected, I can merge it.

**Comment by enzococca** [comment]
Hi Stefano, for me you can merge

E

Il gio 9 dic 2021, 23:37 Stefano Costa ***@***.***> ha
scritto:

**Review by psolyca — APPROVED** [review]

**Comment by psolyca** [comment]
Hoo sorry forgot this.

**Comment by steko** [comment]
> Hi Stefano, for me you can merge
> 
> E

Thank you @enzococca, if you want you can approve the pull request directly on GitHub.

**Pull request merged**
