### PR TITLE
Nikon npl 322+

### PR DESCRIPTION
**Pull request by baswein**
Hi - I did this a few years ago and wanted to figure out how to test it but never managed to. And was using this again.

### CODE REVIEW

**Review by psolyca — DISMISSED** [review]
Thanks

**Comment by steko** [comment]
I'm not too happy about the `+` character in the filename. If there's no problem I would prefer to replace it with the string `plus`, e.g. `nikon_npl_322plus.py`. Thanks!

**Comment by steko** [comment]
The new model must be added to `totalopenstation-gui.spec`, too:

https://github.com/totalopenstation/totalopenstation/blob/1aad8ae0770f821d06e0c0cae33bff2cfb35f629/totalopenstation-gui.spec#L20

**Review by psolyca — APPROVED** [review]

**Comment by baswein** [comment]
thanks!

**Pull request merged**
