### PR TITLE
Initial skeleton of parametrized test suite, based on pytest

### LINKED ISSUE #85: Test suite doesn't check all possible combinations of input and output formats
When trying to convert one of the sample data files to CSV from the GUI, this happens:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.7/tkinter/simpledialog.py", line 219, in ok
    self.apply()
  File "/home/steko/Scaricati/totalopenstation/scripts/totalopenstation-gui.py", line 309, in apply
    sd_file.write(output.process())
  File "/home/steko/Scaricati/totalopenstation/totalopenstation/output/tops_csv.py", line 53, in process
    feature.point_name,
  File "/home/steko/Scaricati/totalopenstation/totalopenstation/formats/__init__.py", line 52, in point_name
    return self.properties['point_name']
KeyError: 'point_name'
```

This is not caught by our current test suite since the input data used to test the output modules is a fake version. We should run tests in a way that allows testing all input formats against all output formats.

### PR DESCRIPTION
**Pull request by steko**
This pull request closes #85 (without fixing the various bugs that are found).

### CODE REVIEW

**Comment by steko** [comment]
Since we are adding new tests, it is obvious that the Travis checks don't pass.

**Comment by steko** [comment]
The previous test suite had 33 tests, now we are able to perform 99 tests. Of these, currently 32 fail, falling in these 6 categories (number of fails on the left):

```
2 E       AssertionError
1 E       IndexError: list index out of range
7 E       KeyError: 'point_name'
10 E      TypeError: cannot unpack non-iterable Feature object
10 E      TypeError: 'Feature' object is not subscriptable
2 E       ValueError: This point has no z coordinate
```

**Comment by psolyca** [comment]
I am currently on this review but need to know how pytest works ^^

**Comment by steko** [comment]
My local setup for using pytest is like this:

- I create a new virtualenv (preferably isolated from the source tree, e.g. if the source tree is in `/home/steko/code/totalopenstation`, the virtualenv is in `/home/steko/code/envpytest`)
- I install the current working tree in the virtualenv with `pip install -e .`
- I install pytest with `pip install pytest`
- I run pytest with `pytest` in the root directory of the source tree

The output is very verbose, but not very different from running unittest discover or nosetests.

The `@pytest.fixture` decorator is used to make sure the function is called before the actual test. 

The `@pytest.mark.parametrize` decorator is used to run the same test with multiple arguments (in our case, multiple output formats).

**Comment by psolyca** [comment]
Yes, got it working on my virtualenv.
Just need to analyse the report.

**Comment by steko** [comment]
My proposal is to merge this pull request and then fix the many bugs in the code separately, so we can be sure when all are fixed.

**Comment by psolyca** [comment]
OK, we need to take care of the Travis report to avoid missing errors.

**Review by psolyca — APPROVED** [review]

**Pull request merged**
