### PR TITLE
Add Python 3.9 to the CI targets

### PR DESCRIPTION
**Pull request by steko**
This way we can test all Python versions that are currently supported.

### CODE REVIEW

**Review by psolyca — APPROVED** [review]
3.9 passes on Travis CI ^^

**Comment by steko** [comment]
Great! I'm making some experiments with GitHub actions for CI, too.

**Comment by steko** [comment]
On hold since we're evaluating a switch from Travis CI to Github Actions.

**Comment by steko** [comment]
Since the switch yo GitHub actions is taking longer than expected, we can go on with Travis for the time being

**Pull request merged**
